# Generated by Django 4.0.5 on 2022-07-08 19:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('baseAPI', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Emp',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, default='', max_length=100)),
                ('position', models.CharField(blank=True, default='', max_length=100)),
                ('salary', models.TextField()),
                ('start_date', models.DateField()),
                ('office', models.CharField(blank=True, default='', max_length=100)),
                ('extn', models.IntegerField(blank=True, default='')),
            ],
        ),
    ]
