# Generated by Django 4.0.5 on 2022-07-08 19:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('baseAPI', '0003_alter_emp_extn_alter_emp_salary'),
    ]

    operations = [
        migrations.AlterField(
            model_name='emp',
            name='salary',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
    ]
