# Generated by Django 4.0.5 on 2022-07-07 23:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('datatable', '0002_remove_article_content_article_body_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='slug',
            field=models.SlugField(default=0, unique=True),
            preserve_default=False,
        ),
    ]
